#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ENV_FILE="${ENV_FILE:-${SCRIPT_DIR}/openyuanrong.env}"
if [[ -f "${ENV_FILE}" ]]; then
    EXPLICIT_AKERNEL_SERVER_ADDRESS="${AKERNEL_SERVER_ADDRESS-}"
    EXPLICIT_AKERNEL_TOKEN="${AKERNEL_TOKEN-}"
    EXPLICIT_OPENYUANRONG_SERVER_ADDRESS="${OPENYUANRONG_SERVER_ADDRESS-}"
    EXPLICIT_OPENYUANRONG_TOKEN="${OPENYUANRONG_TOKEN-}"
    AKERNEL_SERVER_ADDRESS_WAS_SET="${AKERNEL_SERVER_ADDRESS+x}"
    AKERNEL_TOKEN_WAS_SET="${AKERNEL_TOKEN+x}"
    OPENYUANRONG_SERVER_ADDRESS_WAS_SET="${OPENYUANRONG_SERVER_ADDRESS+x}"
    OPENYUANRONG_TOKEN_WAS_SET="${OPENYUANRONG_TOKEN+x}"

    set -a
    # shellcheck disable=SC1090
    source "${ENV_FILE}"
    set +a

    if [[ -n "${AKERNEL_SERVER_ADDRESS_WAS_SET}" ]]; then
        export AKERNEL_SERVER_ADDRESS="${EXPLICIT_AKERNEL_SERVER_ADDRESS}"
    fi
    if [[ -n "${AKERNEL_TOKEN_WAS_SET}" ]]; then
        export AKERNEL_TOKEN="${EXPLICIT_AKERNEL_TOKEN}"
    fi
    if [[ -n "${OPENYUANRONG_SERVER_ADDRESS_WAS_SET}" ]]; then
        export OPENYUANRONG_SERVER_ADDRESS="${EXPLICIT_OPENYUANRONG_SERVER_ADDRESS}"
    fi
    if [[ -n "${OPENYUANRONG_TOKEN_WAS_SET}" ]]; then
        export OPENYUANRONG_TOKEN="${EXPLICIT_OPENYUANRONG_TOKEN}"
    fi
fi

exec bash "${SCRIPT_DIR}/mini_swe_agent/run_infer.sh" "$@"
